apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-dind
spec:
  selector:
    matchLabels:
      run: alpine-dind
  replicas: 1
  template:
    metadata:
      labels:
        run: alpine-dind
    spec:
      containers:
      - name: alpine-dind
        image: alpine-dind:1.0
        command: [ "bin/ash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: /host
          name: slash
      imagePullSecrets:
      - name: my-secret
      serviceAccount: sa-test
      volumes:
        - hostPath:
            path: /
          name: slash
          