apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
        volumeMounts:
        - name: storage-volume
          mountPath: /usr/share/nginx/html  # Mounting PVC inside the container
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: my-pvc  # Must match an existing PVC

