apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-conf
  namespace: intezer-protect
data:
  nginx.conf: |
  
      worker_processes 4;

      events { worker_connections 1024; }

      http {
        server {
          listen 8080;
          location / {
            proxy_pass http://192.168.1.1;
          }
        }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: intezer-protect
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:1.18.0-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-config-file
            mountPath: /etc/nginx/nginx.conf
      volumes:
      - name: nginx-config-file
        configMap:
          name: nginx-proxy-conf
          items:
          - key: nginx.conf
            path: /etc/nginx/nginx.conf