kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/pv-2/"

